name: Updating Token List

on:
  schedule:
  - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0 
    - name: Setup node/typescript
      run: |
        npm install
    - name: Run AutoUpdateTokens.ts
      run: |
        npx tsc-node src/AutoUpdateTokens.ts
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }} 
      